In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import metrics

# LogisticRegression feature selection

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_wine
wine = load_wine()
print(list(wine.target_names))
print(wine.data)
wine.target[ wine.target ==0 ] = 1 # we use only two classes 
print(wine.target)

['class_0', 'class_1', 'class_2']
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [3]:
X_train, X_test, y_train, y_test = train_test_split( wine.data, wine.target, stratify = wine.target, random_state=42)
print(X_train.shape)

(133, 13)


# Zad

Wykonaj algorytm LogisticRegression z 

* C = 1


In [12]:
from sklearn.linear_model import LogisticRegression
clf1 = LogisticRegression(C=1,random_state=123)
clf1.fit(X_train, y_train)
clf1.coef_

/Users/maja/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[-2.30304177e-01,  6.18807635e-01,  9.46152116e-02,
         1.98568236e-01, -1.77164258e-02, -5.97993897e-01,
        -1.83507168e+00, -1.67572441e-02, -7.18846551e-01,
         1.04532673e+00, -3.79449190e-01, -9.73128111e-01,
         3.39671564e-04]])

# Zad

Wykonaj algorytm LogisticRegression z 

* C = 100


In [13]:
from sklearn.linear_model import LogisticRegression
clf100 = LogisticRegression(C=100,random_state=123)
clf100.fit(X_train, y_train)
clf100.coef_

/Users/maja/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[-0.89044748,  1.38839511,  0.51135104,  0.54206124, -0.02379058,
        -2.03816381, -7.15098081,  0.12241606, -2.4141648 ,  3.07146515,
        -1.31625633, -3.59578531,  0.00806259]])

# Zad

Wykonaj algorytm LogisticRegression z 

* C = 0.01


In [14]:
from sklearn.linear_model import LogisticRegression
clf001 = LogisticRegression(C=0.01,random_state=123)
clf001.fit(X_train, y_train)
clf001.coef_

/Users/maja/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[-0.01061727,  0.13092505,  0.00449712,  0.12806048, -0.01351142,
        -0.07765106, -0.23242301,  0.00347602, -0.06471785,  0.32323237,
        -0.05957354, -0.16151923, -0.00189363]])

# Zad

Na koniec spójrzmy na współrzędne wykorzystywane przez modele z trzema różnymi ustawieniami parametru regularyzacji C

In [17]:
print([clf1.coef_,
clf100.coef_,
clf001.coef_])

[array([[-2.30304177e-01,  6.18807635e-01,  9.46152116e-02,
         1.98568236e-01, -1.77164258e-02, -5.97993897e-01,
        -1.83507168e+00, -1.67572441e-02, -7.18846551e-01,
         1.04532673e+00, -3.79449190e-01, -9.73128111e-01,
         3.39671564e-04]]), array([[-0.89044748,  1.38839511,  0.51135104,  0.54206124, -0.02379058,
        -2.03816381, -7.15098081,  0.12241606, -2.4141648 ,  3.07146515,
        -1.31625633, -3.59578531,  0.00806259]]), array([[-0.01061727,  0.13092505,  0.00449712,  0.12806048, -0.01351142,
        -0.07765106, -0.23242301,  0.00347602, -0.06471785,  0.32323237,
        -0.05957354, -0.16151923, -0.00189363]])]


# Zad

Narysuj wykres współrzędnych wykorzystywane przez modele z trzema różnymi ustawieniami parametru regularyzacji C i regularyzacją L1.